const dataInfo = `
[
    {
        "weight": {
            "imperial": "7  -  10",
            "metric": "3 - 5"
        },
        "id": "abys",
        "name": "Abyssinian",
        "cfa_url": "http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/abyssinian",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/ abyssinian",
        "temperament": "Active, Energetic, Independent, Intelligent, Gentle",
        "origin": "Egypt",
        "country_codes": "EG",
        "country_code": "EG",
        "description": "The Abyssinian is easy to care for, and a joy to have in your   home. They’re affectionate cats and love both people and other animals.",
        "life_span": "14 - 15",
        "indoor": 0,
        "lap": 1,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 3,
        "dog_friendly": 4,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 2,
        "intelligence": 5,
        "shedding_level": 2,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 1,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
        "hypoallergenic": 0,
        "reference_image_id": "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg"
    },
    {
        "weight": {
            "imperial": "7 - 10",
            "metric": "3 - 5"
        },
        "id": "aege",
        "name": "Aegean",
        "vetstreet_url": "http://www.vetstreet.com/cats/aegean-cat",
        "temperament": "Affectionate, Social, Intelligent, Playful, Active",
        "origin": "Greece",
        "country_codes": "GR",
        "country_code": "GR",
        "description": "Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.",
        "life_span": "9 - 12",
        "indoor": 0,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 4,
        "child_friendly": 4,
        "dog_friendly": 4,
        "energy_level": 3,
        "grooming": 3,
        "health_issues": 1,
        "intelligence": 3,
        "shedding_level": 3,
        "social_needs": 4,
        "stranger_friendly": 4,
        "vocalisation": 3,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Aegean_cat",
        "hypoallergenic": 0,
        "reference_image_id": "https://cdn2.thecatapi.com/images/ozEvzdVM-.jpg"
    },
    {
        "weight": {
            "imperial": "7 - 16",
            "metric": "3 - 7"
        },
        "id": "abob",
        "name": "American Bobtail",
        "cfa_url": "http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/american-bobtail",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail",
        "temperament": "Intelligent, Interactive, Lively, Playful, Sensitive",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description": "American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.",
        "life_span": "11 - 15",
        "indoor": 0,
        "lap": 1,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 1,
        "health_issues": 1,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 3,
        "stranger_friendly": 3,
        "vocalisation": 3,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 1,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/American_Bobtail",
        "hypoallergenic": 0,
        "reference_image_id": "https://cdn2.thecatapi.com/images/hBXicehMA.jpg"
    },
    {
        "weight": {
            "imperial": "5 - 10",
            "metric": "2 - 5"
        },
        "id": "acur",
        "name": "American Curl",
        "cfa_url": "http://cfa.org/Breeds/BreedsAB/AmericanCurl.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/american-curl",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/american-curl",
        "temperament": "Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description": "Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.",
        "life_span": "12 - 16",
        "indoor": 0,
        "lap": 1,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 2,
        "health_issues": 1,
        "intelligence": 3,
        "shedding_level": 3,
        "social_needs": 3,
        "stranger_friendly": 3,
        "vocalisation": 3,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/American_Curl",
        "hypoallergenic": 0,
        "reference_image_id": "https://cdn2.thecatapi.com/images/xnsqonbjW.jpg"
    },
    {
        "weight": {
            "imperial": "5 - 10",
            "metric": "2 - 5"
        },
        "id": "orie",
        "name": "Oriental",
        "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/Oriental.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/oriental",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breedsoriental",
        "temperament": "Energetic, Affectionate, Intelligent, Social, Playful,Curious",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description": "Orientals are passionate about the people in their lives.They become extremely attached to their humans, so be prepared for alifetime commitment. When you are not available to entertain her, anOriental will divert herself by jumping on top of the refrigerator, openingdrawers, seeking out new hideaways.",
        "life_span": "12 - 14",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Foreign Type",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 3,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Oriental_Shorthair",
        "hypoallergenic": 1,
        "reference_image_id": "https://cdn2.thecatapi.com/images/LutjkZJpH.jpg"
    },
    {
        "weight": {
            "imperial": "12 - 20",
            "metric": "5 - 9"
        },
        "id": "ragd",
        "name": "Ragdoll",
        "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/ragdoll",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breedragdoll",
        "temperament": "Affectionate, Friendly, Gentle, Quiet, Easygoing",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description": "Ragdolls love their people, greeting them at the doorfollowing them around the house, and leaping into a lap or snuggling ibed whenever given the chance. They are the epitome of a lap cat, enjobeing carried and collapsing into the arms of anyone who holds them.",
        "life_span": "12 - 17",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Rag doll",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 2,
        "health_issues": 3,
        "intelligence": 3,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 3,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Ragdoll",
        "hypoallergenic": 0,
        "reference_image_id": "https://cdn2.thecatapi.com/images/oGefY4YoG.jpg"
    },    
    {
        "weight": {
            "imperial": "5 - 11",
            "metric": "2 - 5"
        },
        "id": "sfol",
        "name": "Scottish Fold",
        "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cascottish-fold-highland-fold",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pcat-breeds/scottish-fold",
        "temperament": "Affectionate, Intelligent, Loyal, Playful, SociaSweet, Loving",
        "origin": "United Kingdom",
        "country_codes": "GB",
        "country_code": "GB",
        "description": "The Scottish Fold is a sweet, charming breed. Sis an easy cat to live with and to care for. She is affectionaand is comfortable with all members of her family. Her tail shoube handled gently. Folds are known for sleeping on their backs, afor sitting with their legs stretched out and their paws on thebelly. This is called the \Buddha Position\",
        "life_span": "11 - 14",
        "indoor": 0,
        "alt_names": "Scot Fold",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 1,
        "health_issues": 4,
        "intelligence": 3,
        "shedding_level": 3,
        "social_needs": 3,
        "stranger_friendly": 3,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Scottish_Fold",
        "hypoallergenic": 0,
        "reference_image_id": "https://cdn2.thecatapi.com/images/o9t0LDcsa.jpg"
    }
]
`